name: Test
on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 11.10.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        run: |-
          npm install -g yarn
          yarn global add bit-bin
      - name: Configure Bit
        run: yarn install
        env:
          BIT_NODE_TOKE: ${{ secrets.BIT_TOKEN }}  
      # - name: Install Dependencies
      #   run: yarn install
      # - name: Run Tests
      #   run: yarn run test:ci
