name: Test
on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.x
      - name: Install yarn
        run: |-
          npm install -g yarn
          yarn global add bit-bin
      - name: Configure Bit
        run: |-
          echo "always-auth=true" >> ~/.npmrc
          echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
          echo "//node.bit.dev/:_authToken={secrets.BIT_NODE_TOKEN}" >> ~/.npmrc
          yarn install
      # - name: Install Dependencies
      #   run: 
      - name: Run Tests
        run: yarn run test:ci
