name: Test
on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.x
      - name: Install yarn
        run: |-
          npm install -g yarn
          yarn global add bit-bin
      - name: Configure Bit
        run: |-
          #   echo "always-auth=true" >> ~/.npmrc
          # echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
          # echo "//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc
            # npm config set '@bit:registry' https://node.bit.dev
            # npm login --registry=https://node.bitsrc.io\n//node.bitsrc.io/:_authToken={secrets.BIT_NODE_TOKEN} 
             echo "Adding bit.dev to npm registry"
          echo "always-auth=true" >> ~/.npmrc
          echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
          echo "//node.bit.dev/:_authToken={secrets.BIT_NODE_TOKEN}" >> ~/.npmrc
          echo "Completed adding bit.dev to npm registry"
          npm config ls
          echo "Show root npmrc"
          cat ~/.npmrc
          # yarn
      # - name: Install Dependencies
      #   run: yarn install
      # - name: Run Tests
      #   run: yarn run test:ci
