
on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.x
      - name: Install yarn
        run: npm install -g yarn
      # - name: Install Bit
      #   run: |-
      #     yarn global add bit-bin
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn run test:ci