name: Test
on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 11.10.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        run: |-
          npm install -g yarn
          yarn global add bit-bin
      - name: Configure Bit
        run: |-
          echo "BAAAAAL"
          npm whoami
          npm config set '@bit:registry' https://node.bit.dev
          npm config ls
          echo "Adding bit.dev to npm registry"
          echo "always-auth=true" >> ~/.npmrc
          echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
          echo "//node.bit.dev/:_authToken={secrets.BIT_NODE_TOKEN}" >> ~/.npmrc
          npm config ls
          yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BIT_TOKEN }}  
      # - name: Install Dependencies
      #   run: yarn install
      # - name: Run Tests
      #   run: yarn run test:ci
